// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.4.3
// Machine:  LUKAS-PC
// DateTime: 9.4.2011 18:45:30
// UserName: Lukas
// Input file <D:\Programovani\VS.2010\SimpleConverter\plugins\Beamer2PPT\Conversion\Parser.y - 9.4.2011 17:02:40>

// options: conflicts no-lines diagnose & report gplex conflicts

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using SimpleConverter.Contract;

namespace SimpleConverter.Plugin.Beamer2PPT
{
public enum Tokens {error=126,
    EOF=127,DOCUMENTCLASS=128,USEPACKAGE=129,USETHEME=130,TITLE=131,AUTHOR=132,
    TODAY=133,DATE=134,TITLEPAGE=135,BEGIN_DOCUMENT=136,END_DOCUMENT=137,BEGIN_FRAME=138,
    END_FRAME=139,FRAME=140,FRAMETITLE=141,FRAMESUBTITLE=142,PAUSE=143,BEGIN_ITEMIZE=144,
    END_ITEMIZE=145,BEGIN_ENUMERATE=146,END_ENUMERATE=147,BEGIN_DESCRIPTION=148,END_DESCRIPTION=149,BEGIN_TABULAR=150,
    END_TABULAR=151,SECTION=152,SUBSECTION=153,SUBSUBSECTION=154,OVERLAY=155,OPTIONAL=156,
    TEXTBF=157,TEXTIT=158,TEXTTT=159,TEXTSC=160,NL=161,ENDROW=162,
    COLOR=163,BFSERIES=164,TTFAMILY=165,ITSHAPE=166,SCSHAPE=167,TINY=168,
    SCRIPTSIZE=169,FOOTNOTESIZE=170,SMALL=171,NORMALSIZE=172,LARGE=173,LARGE2=174,
    LARGE3=175,HUGE=176,HUGE2=177,ITEM=178,UNDERLINE=179,AND=180,
    TEXTCOLOR=181,HLINE=182,CLINE=183,MULTICOLUMN=184,STRING=185};

public struct ValueType
{
    public string Text;
    public Node documentNode;
    public List<Node> nodeList;
    public HashSet<Node> nodeSet;
}
// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
  // Verbatim content from D:\Programovani\VS.2010\SimpleConverter\plugins\Beamer2PPT\Conversion\Parser.y - 9.4.2011 17:02:40
    public Node Document { get; private set; }
    public int SlideCount { get; private set; }
    public List<SectionRecord> SectionTable { get; private set; }
    public Dictionary<int, FrametitleRecord> FrametitleTable { get; private set; }
  // End verbatim content from D:\Programovani\VS.2010\SimpleConverter\plugins\Beamer2PPT\Conversion\Parser.y - 9.4.2011 17:02:40

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[89];
  private static State[] states = new State[215];
  private static string[] nonTerms = new string[] {
      "document", "command", "groupcommand", "standalonecommand", "commands", 
      "slide", "titlesettings", "body", "environment", "documentclass", "preambule", 
      "simpleformtext", "slidecontent", "bodycontent", "items_list", "table_rows", 
      "table_cols", "table_line", "optional", "overlay", "$accept", "sectionsettings", 
      };

  static Parser() {
    states[0] = new State(new int[]{128,210},new int[]{-1,1,-10,3});
    states[1] = new State(new int[]{127,2});
    states[2] = new State(-1);
    states[3] = new State(-4,new int[]{-11,4});
    states[4] = new State(new int[]{129,6,136,16,156,43,131,22,132,83,134,87,130,-76},new int[]{-8,5,-19,10,-7,15});
    states[5] = new State(-2);
    states[6] = new State(new int[]{123,7});
    states[7] = new State(new int[]{185,8});
    states[8] = new State(new int[]{125,9});
    states[9] = new State(-5);
    states[10] = new State(new int[]{130,11});
    states[11] = new State(new int[]{123,12});
    states[12] = new State(new int[]{185,13});
    states[13] = new State(new int[]{125,14});
    states[14] = new State(-6);
    states[15] = new State(-7);
    states[16] = new State(-15,new int[]{-14,17});
    states[17] = new State(new int[]{137,18,131,22,132,83,134,87,152,91,153,95,154,99,138,103,140,206},new int[]{-7,19,-22,20,-6,21});
    states[18] = new State(-14);
    states[19] = new State(-16);
    states[20] = new State(-17);
    states[21] = new State(-18);
    states[22] = new State(new int[]{123,23});
    states[23] = new State(-80,new int[]{-12,24});
    states[24] = new State(new int[]{125,25,185,32,161,33,123,34,133,37,143,38,180,39,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77},new int[]{-2,26,-3,30});
    states[25] = new State(-8);
    states[26] = new State(new int[]{123,27});
    states[27] = new State(-80,new int[]{-12,28});
    states[28] = new State(new int[]{125,29,185,32,161,33,123,34,133,37,143,38,180,39,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77},new int[]{-2,26,-3,30});
    states[29] = new State(-81);
    states[30] = new State(-80,new int[]{-12,31});
    states[31] = new State(new int[]{185,32,161,33,123,34,133,37,143,38,180,39,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77,125,-82},new int[]{-2,26,-3,30});
    states[32] = new State(-83);
    states[33] = new State(-84);
    states[34] = new State(-80,new int[]{-12,35});
    states[35] = new State(new int[]{125,36,185,32,161,33,123,34,133,37,143,38,180,39,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77},new int[]{-2,26,-3,30});
    states[36] = new State(-85);
    states[37] = new State(-86);
    states[38] = new State(-87);
    states[39] = new State(-88);
    states[40] = new State(new int[]{155,44,156,-78,123,-78},new int[]{-20,41});
    states[41] = new State(new int[]{156,43,123,-76},new int[]{-19,42});
    states[42] = new State(-50);
    states[43] = new State(-77);
    states[44] = new State(-79);
    states[45] = new State(new int[]{155,44,156,-78,123,-78},new int[]{-20,46});
    states[46] = new State(new int[]{156,43,123,-76},new int[]{-19,47});
    states[47] = new State(-51);
    states[48] = new State(new int[]{155,44,156,-78,123,-78},new int[]{-20,49});
    states[49] = new State(new int[]{156,43,123,-76},new int[]{-19,50});
    states[50] = new State(-52);
    states[51] = new State(new int[]{155,44,156,-78,123,-78},new int[]{-20,52});
    states[52] = new State(new int[]{156,43,123,-76},new int[]{-19,53});
    states[53] = new State(-53);
    states[54] = new State(new int[]{155,44,156,-78,123,-78},new int[]{-20,55});
    states[55] = new State(new int[]{156,43,123,-76},new int[]{-19,56});
    states[56] = new State(-54);
    states[57] = new State(new int[]{155,44,156,-78,123,-78},new int[]{-20,58});
    states[58] = new State(new int[]{156,43,123,-76},new int[]{-19,59});
    states[59] = new State(new int[]{123,60});
    states[60] = new State(new int[]{185,61});
    states[61] = new State(new int[]{125,62});
    states[62] = new State(-55);
    states[63] = new State(-56);
    states[64] = new State(-57);
    states[65] = new State(-58);
    states[66] = new State(-59);
    states[67] = new State(-60);
    states[68] = new State(-61);
    states[69] = new State(-62);
    states[70] = new State(-63);
    states[71] = new State(-64);
    states[72] = new State(-65);
    states[73] = new State(-66);
    states[74] = new State(-67);
    states[75] = new State(-68);
    states[76] = new State(-69);
    states[77] = new State(new int[]{155,44,156,-78,123,-78},new int[]{-20,78});
    states[78] = new State(new int[]{156,43,123,-76},new int[]{-19,79});
    states[79] = new State(new int[]{123,80});
    states[80] = new State(new int[]{185,81});
    states[81] = new State(new int[]{125,82});
    states[82] = new State(-70);
    states[83] = new State(new int[]{123,84});
    states[84] = new State(-80,new int[]{-12,85});
    states[85] = new State(new int[]{125,86,185,32,161,33,123,34,133,37,143,38,180,39,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77},new int[]{-2,26,-3,30});
    states[86] = new State(-9);
    states[87] = new State(new int[]{123,88});
    states[88] = new State(-80,new int[]{-12,89});
    states[89] = new State(new int[]{125,90,185,32,161,33,123,34,133,37,143,38,180,39,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77},new int[]{-2,26,-3,30});
    states[90] = new State(-10);
    states[91] = new State(new int[]{123,92});
    states[92] = new State(-80,new int[]{-12,93});
    states[93] = new State(new int[]{125,94,185,32,161,33,123,34,133,37,143,38,180,39,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77},new int[]{-2,26,-3,30});
    states[94] = new State(-11);
    states[95] = new State(new int[]{123,96});
    states[96] = new State(-80,new int[]{-12,97});
    states[97] = new State(new int[]{125,98,185,32,161,33,123,34,133,37,143,38,180,39,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77},new int[]{-2,26,-3,30});
    states[98] = new State(-12);
    states[99] = new State(new int[]{123,100});
    states[100] = new State(-80,new int[]{-12,101});
    states[101] = new State(new int[]{125,102,185,32,161,33,123,34,133,37,143,38,180,39,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77},new int[]{-2,26,-3,30});
    states[102] = new State(-13);
    states[103] = new State(new int[]{123,196,139,-23,185,-23,152,-23,153,-23,154,-23,144,-23,146,-23,148,-23,150,-23,157,-23,158,-23,159,-23,160,-23,179,-23,181,-23,164,-23,165,-23,166,-23,167,-23,168,-23,169,-23,170,-23,171,-23,172,-23,173,-23,174,-23,175,-23,176,-23,177,-23,163,-23,133,-23,143,-23,141,-23,142,-23,161,-23},new int[]{-13,104});
    states[104] = new State(new int[]{139,105,123,106,185,109,152,91,153,95,154,99,144,113,146,120,148,127,150,130,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77,133,145,143,146,141,147,142,153,161,159},new int[]{-22,110,-9,111,-5,112,-2,138,-3,142,-4,144});
    states[105] = new State(-19);
    states[106] = new State(-23,new int[]{-13,107});
    states[107] = new State(new int[]{125,108,123,106,185,109,152,91,153,95,154,99,144,113,146,120,148,127,150,130,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77,133,145,143,146,141,147,142,153,161,159},new int[]{-22,110,-9,111,-5,112,-2,138,-3,142,-4,144});
    states[108] = new State(-24);
    states[109] = new State(-25);
    states[110] = new State(-26);
    states[111] = new State(-27);
    states[112] = new State(-28);
    states[113] = new State(new int[]{178,123},new int[]{-15,114});
    states[114] = new State(new int[]{145,115,178,116});
    states[115] = new State(-29);
    states[116] = new State(new int[]{155,44,156,-78,123,-78,185,-78,152,-78,153,-78,154,-78,144,-78,146,-78,148,-78,150,-78,157,-78,158,-78,159,-78,160,-78,179,-78,181,-78,164,-78,165,-78,166,-78,167,-78,168,-78,169,-78,170,-78,171,-78,172,-78,173,-78,174,-78,175,-78,176,-78,177,-78,163,-78,133,-78,143,-78,141,-78,142,-78,161,-78,145,-78,178,-78,147,-78,149,-78},new int[]{-20,117});
    states[117] = new State(new int[]{156,43,123,-76,185,-76,152,-76,153,-76,154,-76,144,-76,146,-76,148,-76,150,-76,157,-76,158,-76,159,-76,160,-76,179,-76,181,-76,164,-76,165,-76,166,-76,167,-76,168,-76,169,-76,170,-76,171,-76,172,-76,173,-76,174,-76,175,-76,176,-76,177,-76,163,-76,133,-76,143,-76,141,-76,142,-76,161,-76,145,-76,178,-76,147,-76,149,-76},new int[]{-19,118});
    states[118] = new State(-23,new int[]{-13,119});
    states[119] = new State(new int[]{123,106,185,109,152,91,153,95,154,99,144,113,146,120,148,127,150,130,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77,133,145,143,146,141,147,142,153,161,159,145,-34,178,-34,147,-34,149,-34},new int[]{-22,110,-9,111,-5,112,-2,138,-3,142,-4,144});
    states[120] = new State(new int[]{178,123},new int[]{-15,121});
    states[121] = new State(new int[]{147,122,178,116});
    states[122] = new State(-30);
    states[123] = new State(new int[]{155,44,156,-78,123,-78,185,-78,152,-78,153,-78,154,-78,144,-78,146,-78,148,-78,150,-78,157,-78,158,-78,159,-78,160,-78,179,-78,181,-78,164,-78,165,-78,166,-78,167,-78,168,-78,169,-78,170,-78,171,-78,172,-78,173,-78,174,-78,175,-78,176,-78,177,-78,163,-78,133,-78,143,-78,141,-78,142,-78,161,-78,145,-78,178,-78,147,-78,149,-78},new int[]{-20,124});
    states[124] = new State(new int[]{156,43,123,-76,185,-76,152,-76,153,-76,154,-76,144,-76,146,-76,148,-76,150,-76,157,-76,158,-76,159,-76,160,-76,179,-76,181,-76,164,-76,165,-76,166,-76,167,-76,168,-76,169,-76,170,-76,171,-76,172,-76,173,-76,174,-76,175,-76,176,-76,177,-76,163,-76,133,-76,143,-76,141,-76,142,-76,161,-76,145,-76,178,-76,147,-76,149,-76},new int[]{-19,125});
    states[125] = new State(-23,new int[]{-13,126});
    states[126] = new State(new int[]{123,106,185,109,152,91,153,95,154,99,144,113,146,120,148,127,150,130,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77,133,145,143,146,141,147,142,153,161,159,145,-33,178,-33,147,-33,149,-33},new int[]{-22,110,-9,111,-5,112,-2,138,-3,142,-4,144});
    states[127] = new State(new int[]{178,123},new int[]{-15,128});
    states[128] = new State(new int[]{149,129,178,116});
    states[129] = new State(-31);
    states[130] = new State(new int[]{185,131});
    states[131] = new State(new int[]{184,178,182,188,183,189,123,-23,185,-23,152,-23,153,-23,154,-23,144,-23,146,-23,148,-23,150,-23,157,-23,158,-23,159,-23,160,-23,179,-23,181,-23,164,-23,165,-23,166,-23,167,-23,168,-23,169,-23,170,-23,171,-23,172,-23,173,-23,174,-23,175,-23,176,-23,177,-23,163,-23,133,-23,143,-23,141,-23,142,-23,161,-23,38,-23,151,-23,162,-23},new int[]{-16,132,-17,193,-13,177,-18,194});
    states[132] = new State(new int[]{151,133,162,134});
    states[133] = new State(-32);
    states[134] = new State(new int[]{184,178,182,188,183,189,123,-23,185,-23,152,-23,153,-23,154,-23,144,-23,146,-23,148,-23,150,-23,157,-23,158,-23,159,-23,160,-23,179,-23,181,-23,164,-23,165,-23,166,-23,167,-23,168,-23,169,-23,170,-23,171,-23,172,-23,173,-23,174,-23,175,-23,176,-23,177,-23,163,-23,133,-23,143,-23,141,-23,142,-23,161,-23,38,-23,151,-23,162,-23},new int[]{-17,135,-18,170,-13,177});
    states[135] = new State(new int[]{38,136,151,-37,162,-37});
    states[136] = new State(new int[]{184,160,123,-23,185,-23,152,-23,153,-23,154,-23,144,-23,146,-23,148,-23,150,-23,157,-23,158,-23,159,-23,160,-23,179,-23,181,-23,164,-23,165,-23,166,-23,167,-23,168,-23,169,-23,170,-23,171,-23,172,-23,173,-23,174,-23,175,-23,176,-23,177,-23,163,-23,133,-23,143,-23,141,-23,142,-23,161,-23,38,-23,151,-23,162,-23},new int[]{-13,137});
    states[137] = new State(new int[]{123,106,185,109,152,91,153,95,154,99,144,113,146,120,148,127,150,130,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77,133,145,143,146,141,147,142,153,161,159,38,-45,151,-45,162,-45},new int[]{-22,110,-9,111,-5,112,-2,138,-3,142,-4,144});
    states[138] = new State(new int[]{123,139});
    states[139] = new State(-23,new int[]{-13,140});
    states[140] = new State(new int[]{125,141,123,106,185,109,152,91,153,95,154,99,144,113,146,120,148,127,150,130,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77,133,145,143,146,141,147,142,153,161,159},new int[]{-22,110,-9,111,-5,112,-2,138,-3,142,-4,144});
    states[141] = new State(-47);
    states[142] = new State(-23,new int[]{-13,143});
    states[143] = new State(new int[]{123,106,185,109,152,91,153,95,154,99,144,113,146,120,148,127,150,130,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77,133,145,143,146,141,147,142,153,161,159,139,-48,125,-48,145,-48,178,-48,147,-48,149,-48,38,-48,151,-48,162,-48},new int[]{-22,110,-9,111,-5,112,-2,138,-3,142,-4,144});
    states[144] = new State(-49);
    states[145] = new State(-71);
    states[146] = new State(-72);
    states[147] = new State(new int[]{155,44,156,-78,123,-78},new int[]{-20,148});
    states[148] = new State(new int[]{156,43,123,-76},new int[]{-19,149});
    states[149] = new State(new int[]{123,150});
    states[150] = new State(-80,new int[]{-12,151});
    states[151] = new State(new int[]{125,152,185,32,161,33,123,34,133,37,143,38,180,39,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77},new int[]{-2,26,-3,30});
    states[152] = new State(-73);
    states[153] = new State(new int[]{155,44,156,-78,123,-78},new int[]{-20,154});
    states[154] = new State(new int[]{156,43,123,-76},new int[]{-19,155});
    states[155] = new State(new int[]{123,156});
    states[156] = new State(-80,new int[]{-12,157});
    states[157] = new State(new int[]{125,158,185,32,161,33,123,34,133,37,143,38,180,39,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77},new int[]{-2,26,-3,30});
    states[158] = new State(-74);
    states[159] = new State(-75);
    states[160] = new State(new int[]{123,161});
    states[161] = new State(new int[]{185,162});
    states[162] = new State(new int[]{125,163});
    states[163] = new State(new int[]{123,164});
    states[164] = new State(new int[]{185,165});
    states[165] = new State(new int[]{125,166});
    states[166] = new State(new int[]{123,167});
    states[167] = new State(-23,new int[]{-13,168});
    states[168] = new State(new int[]{125,169,123,106,185,109,152,91,153,95,154,99,144,113,146,120,148,127,150,130,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77,133,145,143,146,141,147,142,153,161,159},new int[]{-22,110,-9,111,-5,112,-2,138,-3,142,-4,144});
    states[169] = new State(-46);
    states[170] = new State(new int[]{182,172,183,173,184,178,123,-23,185,-23,152,-23,153,-23,154,-23,144,-23,146,-23,148,-23,150,-23,157,-23,158,-23,159,-23,160,-23,179,-23,181,-23,164,-23,165,-23,166,-23,167,-23,168,-23,169,-23,170,-23,171,-23,172,-23,173,-23,174,-23,175,-23,176,-23,177,-23,163,-23,133,-23,143,-23,141,-23,142,-23,161,-23,38,-23,151,-23,162,-23},new int[]{-17,171,-13,177});
    states[171] = new State(new int[]{38,136,151,-38,162,-38});
    states[172] = new State(-41);
    states[173] = new State(new int[]{123,174});
    states[174] = new State(new int[]{185,175});
    states[175] = new State(new int[]{125,176});
    states[176] = new State(-42);
    states[177] = new State(new int[]{123,106,185,109,152,91,153,95,154,99,144,113,146,120,148,127,150,130,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77,133,145,143,146,141,147,142,153,161,159,38,-43,151,-43,162,-43},new int[]{-22,110,-9,111,-5,112,-2,138,-3,142,-4,144});
    states[178] = new State(new int[]{123,179});
    states[179] = new State(new int[]{185,180});
    states[180] = new State(new int[]{125,181});
    states[181] = new State(new int[]{123,182});
    states[182] = new State(new int[]{185,183});
    states[183] = new State(new int[]{125,184});
    states[184] = new State(new int[]{123,185});
    states[185] = new State(-23,new int[]{-13,186});
    states[186] = new State(new int[]{125,187,123,106,185,109,152,91,153,95,154,99,144,113,146,120,148,127,150,130,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77,133,145,143,146,141,147,142,153,161,159},new int[]{-22,110,-9,111,-5,112,-2,138,-3,142,-4,144});
    states[187] = new State(-44);
    states[188] = new State(-39);
    states[189] = new State(new int[]{123,190});
    states[190] = new State(new int[]{185,191});
    states[191] = new State(new int[]{125,192});
    states[192] = new State(-40);
    states[193] = new State(new int[]{38,136,151,-35,162,-35});
    states[194] = new State(new int[]{182,172,183,173,184,178,123,-23,185,-23,152,-23,153,-23,154,-23,144,-23,146,-23,148,-23,150,-23,157,-23,158,-23,159,-23,160,-23,179,-23,181,-23,164,-23,165,-23,166,-23,167,-23,168,-23,169,-23,170,-23,171,-23,172,-23,173,-23,174,-23,175,-23,176,-23,177,-23,163,-23,133,-23,143,-23,141,-23,142,-23,161,-23,38,-23,151,-23,162,-23},new int[]{-17,195,-13,177});
    states[195] = new State(new int[]{38,136,151,-36,162,-36});
    states[196] = new State(-80,new int[]{-12,197});
    states[197] = new State(new int[]{125,198,185,32,161,33,123,34,133,37,143,38,180,39,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77},new int[]{-2,26,-3,30});
    states[198] = new State(new int[]{123,201,139,-23,185,-23,152,-23,153,-23,154,-23,144,-23,146,-23,148,-23,150,-23,157,-23,158,-23,159,-23,160,-23,179,-23,181,-23,164,-23,165,-23,166,-23,167,-23,168,-23,169,-23,170,-23,171,-23,172,-23,173,-23,174,-23,175,-23,176,-23,177,-23,163,-23,133,-23,143,-23,141,-23,142,-23,161,-23},new int[]{-13,199});
    states[199] = new State(new int[]{139,200,123,106,185,109,152,91,153,95,154,99,144,113,146,120,148,127,150,130,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77,133,145,143,146,141,147,142,153,161,159},new int[]{-22,110,-9,111,-5,112,-2,138,-3,142,-4,144});
    states[200] = new State(-20);
    states[201] = new State(-80,new int[]{-12,202});
    states[202] = new State(new int[]{125,203,185,32,161,33,123,34,133,37,143,38,180,39,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77},new int[]{-2,26,-3,30});
    states[203] = new State(-23,new int[]{-13,204});
    states[204] = new State(new int[]{139,205,123,106,185,109,152,91,153,95,154,99,144,113,146,120,148,127,150,130,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77,133,145,143,146,141,147,142,153,161,159},new int[]{-22,110,-9,111,-5,112,-2,138,-3,142,-4,144});
    states[205] = new State(-21);
    states[206] = new State(new int[]{123,207});
    states[207] = new State(-23,new int[]{-13,208});
    states[208] = new State(new int[]{125,209,123,106,185,109,152,91,153,95,154,99,144,113,146,120,148,127,150,130,157,40,158,45,159,48,160,51,179,54,181,57,164,63,165,64,166,65,167,66,168,67,169,68,170,69,171,70,172,71,173,72,174,73,175,74,176,75,177,76,163,77,133,145,143,146,141,147,142,153,161,159},new int[]{-22,110,-9,111,-5,112,-2,138,-3,142,-4,144});
    states[209] = new State(-22);
    states[210] = new State(new int[]{156,43,123,-76},new int[]{-19,211});
    states[211] = new State(new int[]{123,212});
    states[212] = new State(new int[]{185,213});
    states[213] = new State(new int[]{125,214});
    states[214] = new State(-3);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-21, new int[]{-1,127});
    rules[2] = new Rule(-1, new int[]{-10,-11,-8});
    rules[3] = new Rule(-10, new int[]{128,-19,123,185,125});
    rules[4] = new Rule(-11, new int[]{});
    rules[5] = new Rule(-11, new int[]{-11,129,123,185,125});
    rules[6] = new Rule(-11, new int[]{-11,-19,130,123,185,125});
    rules[7] = new Rule(-11, new int[]{-11,-7});
    rules[8] = new Rule(-7, new int[]{131,123,-12,125});
    rules[9] = new Rule(-7, new int[]{132,123,-12,125});
    rules[10] = new Rule(-7, new int[]{134,123,-12,125});
    rules[11] = new Rule(-22, new int[]{152,123,-12,125});
    rules[12] = new Rule(-22, new int[]{153,123,-12,125});
    rules[13] = new Rule(-22, new int[]{154,123,-12,125});
    rules[14] = new Rule(-8, new int[]{136,-14,137});
    rules[15] = new Rule(-14, new int[]{});
    rules[16] = new Rule(-14, new int[]{-14,-7});
    rules[17] = new Rule(-14, new int[]{-14,-22});
    rules[18] = new Rule(-14, new int[]{-14,-6});
    rules[19] = new Rule(-6, new int[]{138,-13,139});
    rules[20] = new Rule(-6, new int[]{138,123,-12,125,-13,139});
    rules[21] = new Rule(-6, new int[]{138,123,-12,125,123,-12,125,-13,139});
    rules[22] = new Rule(-6, new int[]{140,123,-13,125});
    rules[23] = new Rule(-13, new int[]{});
    rules[24] = new Rule(-13, new int[]{-13,123,-13,125});
    rules[25] = new Rule(-13, new int[]{-13,185});
    rules[26] = new Rule(-13, new int[]{-13,-22});
    rules[27] = new Rule(-13, new int[]{-13,-9});
    rules[28] = new Rule(-13, new int[]{-13,-5});
    rules[29] = new Rule(-9, new int[]{144,-15,145});
    rules[30] = new Rule(-9, new int[]{146,-15,147});
    rules[31] = new Rule(-9, new int[]{148,-15,149});
    rules[32] = new Rule(-9, new int[]{150,185,-16,151});
    rules[33] = new Rule(-15, new int[]{178,-20,-19,-13});
    rules[34] = new Rule(-15, new int[]{-15,178,-20,-19,-13});
    rules[35] = new Rule(-16, new int[]{-17});
    rules[36] = new Rule(-16, new int[]{-18,-17});
    rules[37] = new Rule(-16, new int[]{-16,162,-17});
    rules[38] = new Rule(-16, new int[]{-16,162,-18,-17});
    rules[39] = new Rule(-18, new int[]{182});
    rules[40] = new Rule(-18, new int[]{183,123,185,125});
    rules[41] = new Rule(-18, new int[]{-18,182});
    rules[42] = new Rule(-18, new int[]{-18,183,123,185,125});
    rules[43] = new Rule(-17, new int[]{-13});
    rules[44] = new Rule(-17, new int[]{184,123,185,125,123,185,125,123,-13,125});
    rules[45] = new Rule(-17, new int[]{-17,38,-13});
    rules[46] = new Rule(-17, new int[]{-17,38,184,123,185,125,123,185,125,123,-13,125});
    rules[47] = new Rule(-5, new int[]{-2,123,-13,125});
    rules[48] = new Rule(-5, new int[]{-3,-13});
    rules[49] = new Rule(-5, new int[]{-4});
    rules[50] = new Rule(-2, new int[]{157,-20,-19});
    rules[51] = new Rule(-2, new int[]{158,-20,-19});
    rules[52] = new Rule(-2, new int[]{159,-20,-19});
    rules[53] = new Rule(-2, new int[]{160,-20,-19});
    rules[54] = new Rule(-2, new int[]{179,-20,-19});
    rules[55] = new Rule(-2, new int[]{181,-20,-19,123,185,125});
    rules[56] = new Rule(-3, new int[]{164});
    rules[57] = new Rule(-3, new int[]{165});
    rules[58] = new Rule(-3, new int[]{166});
    rules[59] = new Rule(-3, new int[]{167});
    rules[60] = new Rule(-3, new int[]{168});
    rules[61] = new Rule(-3, new int[]{169});
    rules[62] = new Rule(-3, new int[]{170});
    rules[63] = new Rule(-3, new int[]{171});
    rules[64] = new Rule(-3, new int[]{172});
    rules[65] = new Rule(-3, new int[]{173});
    rules[66] = new Rule(-3, new int[]{174});
    rules[67] = new Rule(-3, new int[]{175});
    rules[68] = new Rule(-3, new int[]{176});
    rules[69] = new Rule(-3, new int[]{177});
    rules[70] = new Rule(-3, new int[]{163,-20,-19,123,185,125});
    rules[71] = new Rule(-4, new int[]{133});
    rules[72] = new Rule(-4, new int[]{143});
    rules[73] = new Rule(-4, new int[]{141,-20,-19,123,-12,125});
    rules[74] = new Rule(-4, new int[]{142,-20,-19,123,-12,125});
    rules[75] = new Rule(-4, new int[]{161});
    rules[76] = new Rule(-19, new int[]{});
    rules[77] = new Rule(-19, new int[]{156});
    rules[78] = new Rule(-20, new int[]{});
    rules[79] = new Rule(-20, new int[]{155});
    rules[80] = new Rule(-12, new int[]{});
    rules[81] = new Rule(-12, new int[]{-12,-2,123,-12,125});
    rules[82] = new Rule(-12, new int[]{-12,-3,-12});
    rules[83] = new Rule(-12, new int[]{-12,185});
    rules[84] = new Rule(-12, new int[]{-12,161});
    rules[85] = new Rule(-12, new int[]{-12,123,-12,125});
    rules[86] = new Rule(-12, new int[]{-12,133});
    rules[87] = new Rule(-12, new int[]{-12,143});
    rules[88] = new Rule(-12, new int[]{-12,180});

    aliasses = new Dictionary<int, string>();
    aliasses.Add(128, "\"\\documentclass\"");
    aliasses.Add(129, "\"\\usepackage\"");
    aliasses.Add(130, "\"\\usetheme\"");
    aliasses.Add(131, "\"\\title\"");
    aliasses.Add(132, "\"\\author\"");
    aliasses.Add(133, "\"\\today\"");
    aliasses.Add(134, "\"\\date\"");
    aliasses.Add(135, "\"\\titlepage\"");
    aliasses.Add(136, "\"\\begin{document}\"");
    aliasses.Add(137, "\"\\end{document}\"");
    aliasses.Add(138, "\"\\begin{frame}\"");
    aliasses.Add(139, "\"\\end{frame}\"");
    aliasses.Add(140, "\"\\frame\"");
    aliasses.Add(141, "\"\\frametitle\"");
    aliasses.Add(142, "\"\\framesubtitle\"");
    aliasses.Add(143, "\"\\pause\"");
    aliasses.Add(144, "\"\\begin{itemize}\"");
    aliasses.Add(145, "\"\\end{itemize}\"");
    aliasses.Add(146, "\"\\begin{enumerate}\"");
    aliasses.Add(147, "\"\\end{enumerate}\"");
    aliasses.Add(148, "\"\\begin{description}\"");
    aliasses.Add(149, "\"\\end{description}\"");
    aliasses.Add(150, "\"\\begin{tabular}\"");
    aliasses.Add(151, "\"\\end{tabular}\"");
    aliasses.Add(152, "\"\\section\"");
    aliasses.Add(153, "\"\\subsection\"");
    aliasses.Add(154, "\"\\subsubsection\"");
    aliasses.Add(155, "\"overlay\x20specification\"");
    aliasses.Add(156, "\"optional\x20parameter\"");
    aliasses.Add(157, "\"\\textbf\"");
    aliasses.Add(158, "\"\\textit\"");
    aliasses.Add(159, "\"\\texttt\"");
    aliasses.Add(160, "\"\\textsc\"");
    aliasses.Add(161, "\"\\\\\x20or\x20\\cr\"");
    aliasses.Add(162, "\"\\\\\x20or\x20\\cr\"");
    aliasses.Add(163, "\"\\color\"");
    aliasses.Add(164, "\"\\bfseries\"");
    aliasses.Add(165, "\"\\ttfamily\"");
    aliasses.Add(166, "\"\\itshape\"");
    aliasses.Add(167, "\"\\scshape\"");
    aliasses.Add(168, "\"\\tiny\"");
    aliasses.Add(169, "\"\\scriptsize\"");
    aliasses.Add(170, "\"\\footnotesize\"");
    aliasses.Add(171, "\"\\small\"");
    aliasses.Add(172, "\"\\normalsize\"");
    aliasses.Add(173, "\"\\large\"");
    aliasses.Add(174, "\"\\Large\"");
    aliasses.Add(175, "\"\\LARGE\"");
    aliasses.Add(176, "\"\\huge\"");
    aliasses.Add(177, "\"\\Huge\"");
    aliasses.Add(178, "\"\\item\"");
    aliasses.Add(179, "\"\\underline\"");
    aliasses.Add(180, "\"\\and\"");
    aliasses.Add(181, "\"\\textcolor\"");
    aliasses.Add(182, "\"\\hline\"");
    aliasses.Add(183, "\"\\cline\"");
    aliasses.Add(184, "\"\\multicolumn\"");
    aliasses.Add(185, "\"plain\x20text\"");
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
    switch (action)
    {
      case 2: // document -> documentclass, preambule, body
{
                                        Document = ValueStack[ValueStack.Depth-3].documentNode;
                                        Document.Children = new List<Node>();
                                        Document.Children.Add(ValueStack[ValueStack.Depth-2].documentNode);
                                        Document.Children.Add(ValueStack[ValueStack.Depth-1].documentNode);
                                    }
        break;
      case 3: // documentclass -> "\documentclass", optional, '{', "plain text", '}'
{
                                        if(String.Compare(ValueStack[ValueStack.Depth-2].Text, "beamer", false) != 0) {
                                            Messenger.Instance.SendMessage("Invalid document class \"" + ValueStack[ValueStack.Depth-2].Text + "\"", MessageLevel.WARNING);
                                        }
                                        CurrentSemanticValue.documentNode = new Node("document");
                                        CurrentSemanticValue.documentNode.OptionalParams = ValueStack[ValueStack.Depth-4].Text;
                                    }
        break;
      case 4: // preambule -> /* empty */
{
                                        CurrentSemanticValue.documentNode = new Node("preambule");
                                        CurrentSemanticValue.documentNode.Children = new List<Node>();
                                    }
        break;
      case 5: // preambule -> preambule, "\usepackage", '{', "plain text", '}'
{   // really need to process??
                                        Node tmp = new Node("package");
                                        tmp.Content = ValueStack[ValueStack.Depth-2].Text as object;
                                        ValueStack[ValueStack.Depth-5].documentNode.Children.Add(tmp);
                                        CurrentSemanticValue.documentNode = ValueStack[ValueStack.Depth-5].documentNode;
                                    }
        break;
      case 6: // preambule -> preambule, optional, "\usetheme", '{', "plain text", '}'
{
                                        Node tmp = new Node("theme");
                                        tmp.Content = ValueStack[ValueStack.Depth-2].Text as object;
                                        tmp.OptionalParams = ValueStack[ValueStack.Depth-5].Text;
                                        ValueStack[ValueStack.Depth-6].documentNode.Children.Add(tmp);
                                        CurrentSemanticValue.documentNode = ValueStack[ValueStack.Depth-6].documentNode;
                                    }
        break;
      case 7: // preambule -> preambule, titlesettings
{
                                        ValueStack[ValueStack.Depth-2].documentNode.Children.Add(ValueStack[ValueStack.Depth-1].documentNode);
                                        CurrentSemanticValue.documentNode = ValueStack[ValueStack.Depth-2].documentNode;
                                    }
        break;
      case 8: // titlesettings -> "\title", '{', simpleformtext, '}'
{
                                        CurrentSemanticValue.documentNode = new Node("title");
                                        CurrentSemanticValue.documentNode.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 9: // titlesettings -> "\author", '{', simpleformtext, '}'
{ // todo: can contain \and command
                                        CurrentSemanticValue.documentNode = new Node("author");
                                        CurrentSemanticValue.documentNode.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 10: // titlesettings -> "\date", '{', simpleformtext, '}'
{
                                        CurrentSemanticValue.documentNode = new Node("date");
                                        CurrentSemanticValue.documentNode.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 11: // sectionsettings -> "\section", '{', simpleformtext, '}'
{
                                        SectionTable.Add(new SectionRecord(SlideCount + 1, ValueStack[ValueStack.Depth-2].nodeList));
                                    }
        break;
      case 12: // sectionsettings -> "\subsection", '{', simpleformtext, '}'
{
                                        SectionTable.Add(new SectionRecord(SlideCount + 1, ValueStack[ValueStack.Depth-2].nodeList, SectionType.SUBSECTION));
                                    }
        break;
      case 13: // sectionsettings -> "\subsubsection", '{', simpleformtext, '}'
{
                                        SectionTable.Add(new SectionRecord(SlideCount + 1, ValueStack[ValueStack.Depth-2].nodeList, SectionType.SUBSUBSECTION));
                                    }
        break;
      case 14: // body -> "\begin{document}", bodycontent, "\end{document}"
{
                                        CurrentSemanticValue.documentNode = new Node("body");
                                        CurrentSemanticValue.documentNode.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 15: // bodycontent -> /* empty */
{
                                        CurrentSemanticValue.nodeList = new List<Node>();
                                    }
        break;
      case 16: // bodycontent -> bodycontent, titlesettings
{
                                        ValueStack[ValueStack.Depth-2].nodeList.Add(ValueStack[ValueStack.Depth-1].documentNode);
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 17: // bodycontent -> bodycontent, sectionsettings
{
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 18: // bodycontent -> bodycontent, slide
{
                                        ValueStack[ValueStack.Depth-2].nodeList.Add(ValueStack[ValueStack.Depth-1].documentNode);
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 19: // slide -> "\begin{frame}", slidecontent, "\end{frame}"
{
                                        CurrentSemanticValue.documentNode = new Node("slide");
                                        CurrentSemanticValue.documentNode.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                        SlideCount++;
                                    }
        break;
      case 20: // slide -> "\begin{frame}", '{', simpleformtext, '}', slidecontent, "\end{frame}"
{
                                        CurrentSemanticValue.documentNode = new Node("slide");
                                        CurrentSemanticValue.documentNode.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                        SlideCount++;
                                        SetFrameTitle(SlideCount, ValueStack[ValueStack.Depth-4].nodeList);
                                    }
        break;
      case 21: // slide -> "\begin{frame}", '{', simpleformtext, '}', '{', simpleformtext, '}', 
               //          slidecontent, "\end{frame}"
{
                                        CurrentSemanticValue.documentNode = new Node("slide");
                                        CurrentSemanticValue.documentNode.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                        SlideCount++;
                                        SetFrameTitle(SlideCount, ValueStack[ValueStack.Depth-7].nodeList);
                                        SetFrameSubtitle(SlideCount, ValueStack[ValueStack.Depth-4].nodeList);
                                    }
        break;
      case 22: // slide -> "\frame", '{', slidecontent, '}'
{
                                        CurrentSemanticValue.documentNode = new Node("slide");
                                        CurrentSemanticValue.documentNode.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                        SlideCount++;
                                    }
        break;
      case 23: // slidecontent -> /* empty */
{   /* return List<Node> - create node in specific command; append right side to the left side*/
                                        CurrentSemanticValue.nodeList = new List<Node>();
                                    }
        break;
      case 24: // slidecontent -> slidecontent, '{', slidecontent, '}'
{
                                        Node tmp = new Node("block");
                                        tmp.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                        ValueStack[ValueStack.Depth-4].nodeList.Add(tmp);
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-4].nodeList;
                                    }
        break;
      case 25: // slidecontent -> slidecontent, "plain text"
{
                                        Node tmp = new Node("string");
                                        tmp.Content = ValueStack[ValueStack.Depth-1].Text as object;
                                        ValueStack[ValueStack.Depth-2].nodeList.Add(tmp);
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 26: // slidecontent -> slidecontent, sectionsettings
{
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 27: // slidecontent -> slidecontent, environment
{
                                        ValueStack[ValueStack.Depth-2].nodeList.Add(ValueStack[ValueStack.Depth-1].documentNode);
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 28: // slidecontent -> slidecontent, commands
{
                                        if(ValueStack[ValueStack.Depth-1].documentNode != null) {    // need to check because of frametitle and framesubtitle commands
                                            ValueStack[ValueStack.Depth-2].nodeList.Add(ValueStack[ValueStack.Depth-1].documentNode);
                                        }
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 29: // environment -> "\begin{itemize}", items_list, "\end{itemize}"
{
                                        CurrentSemanticValue.documentNode = new Node("bulletlist");
                                        CurrentSemanticValue.documentNode.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 30: // environment -> "\begin{enumerate}", items_list, "\end{enumerate}"
{
                                        CurrentSemanticValue.documentNode = new Node("numberedlist");
                                        CurrentSemanticValue.documentNode.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 31: // environment -> "\begin{description}", items_list, "\end{description}"
{
                                        CurrentSemanticValue.documentNode = new Node("descriptionlist");
                                        CurrentSemanticValue.documentNode.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 32: // environment -> "\begin{tabular}", "plain text", table_rows, "\end{tabular}"
{
                                        CurrentSemanticValue.documentNode = new Node("table");
                                        CurrentSemanticValue.documentNode.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                        CurrentSemanticValue.documentNode.Content = ValueStack[ValueStack.Depth-3].Text as object;
                                    }
        break;
      case 33: // items_list -> "\item", overlay, optional, slidecontent
{
                                        Node tmp = new Node("item");
                                        tmp.OverlaySpec = ValueStack[ValueStack.Depth-3].Text;
                                        tmp.OptionalParams = ValueStack[ValueStack.Depth-2].Text;
                                        tmp.Children = ValueStack[ValueStack.Depth-1].nodeList;
                                        CurrentSemanticValue.nodeList = new List<Node>();
                                        CurrentSemanticValue.nodeList.Add(tmp);
                                    }
        break;
      case 34: // items_list -> items_list, "\item", overlay, optional, slidecontent
{
                                        Node tmp = new Node("item");
                                        tmp.OverlaySpec = ValueStack[ValueStack.Depth-3].Text;
                                        tmp.OptionalParams = ValueStack[ValueStack.Depth-2].Text;
                                        tmp.Children = ValueStack[ValueStack.Depth-1].nodeList;
                                        ValueStack[ValueStack.Depth-5].nodeList.Add(tmp);
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-5].nodeList;
                                    }
        break;
      case 35: // table_rows -> table_cols
{
                                        Node tmp = new Node("tablerow");
                                        tmp.Children = ValueStack[ValueStack.Depth-1].nodeList;
                                        CurrentSemanticValue.nodeList = new List<Node>();
                                        CurrentSemanticValue.nodeList.Add(tmp);
                                    }
        break;
      case 36: // table_rows -> table_line, table_cols
{
                                        Node tmp = new Node("tablerow");
                                        tmp.Children = ValueStack[ValueStack.Depth-1].nodeList;
                                        CurrentSemanticValue.nodeList = new List<Node>();
                                        CurrentSemanticValue.nodeList.AddRange(ValueStack[ValueStack.Depth-2].nodeSet);
                                        CurrentSemanticValue.nodeList.Add(tmp);
                                    }
        break;
      case 37: // table_rows -> table_rows, "\\ or \cr", table_cols
{
                                        Node tmp = new Node("tablerow");
                                        tmp.Children = ValueStack[ValueStack.Depth-1].nodeList;
                                        ValueStack[ValueStack.Depth-3].nodeList.Add(tmp);
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-3].nodeList;
                                    }
        break;
      case 38: // table_rows -> table_rows, "\\ or \cr", table_line, table_cols
{
                                        Node tmp = new Node("tablerow");
                                        tmp.Children = ValueStack[ValueStack.Depth-1].nodeList;
                                        ValueStack[ValueStack.Depth-4].nodeList.AddRange(ValueStack[ValueStack.Depth-2].nodeSet);
                                        ValueStack[ValueStack.Depth-4].nodeList.Add(tmp);
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-4].nodeList;
                                    }
        break;
      case 39: // table_line -> "\hline"
{
                                        CurrentSemanticValue.nodeSet = new HashSet<Node>();
                                        CurrentSemanticValue.nodeSet.Add(new Node("hline"));
                                    }
        break;
      case 40: // table_line -> "\cline", '{', "plain text", '}'
{
                                        CurrentSemanticValue.nodeSet = new HashSet<Node>();
                                        Node tmp = new Node("cline");
                                        tmp.Content = ValueStack[ValueStack.Depth-2].Text as object;
                                        CurrentSemanticValue.nodeSet.Add(tmp);
                                    }
        break;
      case 41: // table_line -> table_line, "\hline"
{
                                        CurrentSemanticValue.nodeSet.Add(new Node("hline"));
                                    }
        break;
      case 42: // table_line -> table_line, "\cline", '{', "plain text", '}'
{
                                        Node tmp = new Node("cline");
                                        tmp.Content = ValueStack[ValueStack.Depth-2].Text as object;
                                        CurrentSemanticValue.nodeSet.Add(tmp);
                                    }
        break;
      case 43: // table_cols -> slidecontent
{
                                        Node tmp = new Node("tablecolumn");
                                        tmp.Children = ValueStack[ValueStack.Depth-1].nodeList;
                                        CurrentSemanticValue.nodeList = new List<Node>();
                                        CurrentSemanticValue.nodeList.Add(tmp);
                                    }
        break;
      case 44: // table_cols -> "\multicolumn", '{', "plain text", '}', '{', "plain text", '}', 
               //               '{', slidecontent, '}'
{
                                        Node tmp = new Node("tablecolumn_merged");
                                        tmp.Content = ValueStack[ValueStack.Depth-8].Text as object;
                                        tmp.OptionalParams = ValueStack[ValueStack.Depth-5].Text;
                                        tmp.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                        CurrentSemanticValue.nodeList = new List<Node>();
                                        CurrentSemanticValue.nodeList.Add(tmp);
                                    }
        break;
      case 45: // table_cols -> table_cols, '&', slidecontent
{
                                        Node tmp = new Node("tablecolumn");
                                        tmp.Children = ValueStack[ValueStack.Depth-1].nodeList;
                                        ValueStack[ValueStack.Depth-3].nodeList.Add(tmp);
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-3].nodeList;
                                    }
        break;
      case 46: // table_cols -> table_cols, '&', "\multicolumn", '{', "plain text", '}', '{', 
               //               "plain text", '}', '{', slidecontent, '}'
{
                                        Node tmp = new Node("tablecolumn_merged");
                                        tmp.Content = ValueStack[ValueStack.Depth-8].Text as object;
                                        tmp.OptionalParams = ValueStack[ValueStack.Depth-5].Text;
                                        tmp.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                        ValueStack[ValueStack.Depth-12].nodeList.Add(tmp);
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-12].nodeList;
                                    }
        break;
      case 47: // commands -> command, '{', slidecontent, '}'
{
                                        ValueStack[ValueStack.Depth-4].documentNode.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                        CurrentSemanticValue.documentNode = ValueStack[ValueStack.Depth-4].documentNode;
                                    }
        break;
      case 48: // commands -> groupcommand, slidecontent
{
                                        ValueStack[ValueStack.Depth-2].documentNode.Children = ValueStack[ValueStack.Depth-1].nodeList;
                                        CurrentSemanticValue.documentNode = ValueStack[ValueStack.Depth-2].documentNode;
                                    }
        break;
      case 49: // commands -> standalonecommand
{  // e.g. \today, \pause, \\
                                        CurrentSemanticValue.documentNode = ValueStack[ValueStack.Depth-1].documentNode;
                                    }
        break;
      case 50: // command -> "\textbf", overlay, optional
{
                                        CurrentSemanticValue.documentNode = new Node("bold");
                                        CurrentSemanticValue.documentNode.OverlaySpec = ValueStack[ValueStack.Depth-2].Text;
                                        CurrentSemanticValue.documentNode.OptionalParams = ValueStack[ValueStack.Depth-1].Text;
                                    }
        break;
      case 51: // command -> "\textit", overlay, optional
{
                                        CurrentSemanticValue.documentNode = new Node("italic");
                                        CurrentSemanticValue.documentNode.OverlaySpec = ValueStack[ValueStack.Depth-2].Text;
                                        CurrentSemanticValue.documentNode.OptionalParams = ValueStack[ValueStack.Depth-1].Text;
                                    }
        break;
      case 52: // command -> "\texttt", overlay, optional
{
                                        CurrentSemanticValue.documentNode = new Node("typewriter");
                                        CurrentSemanticValue.documentNode.OverlaySpec = ValueStack[ValueStack.Depth-2].Text;
                                        CurrentSemanticValue.documentNode.OptionalParams = ValueStack[ValueStack.Depth-1].Text;
                                    }
        break;
      case 53: // command -> "\textsc", overlay, optional
{
                                        CurrentSemanticValue.documentNode = new Node("smallcaps");
                                        CurrentSemanticValue.documentNode.OverlaySpec = ValueStack[ValueStack.Depth-2].Text;
                                        CurrentSemanticValue.documentNode.OptionalParams = ValueStack[ValueStack.Depth-1].Text;
                                    }
        break;
      case 54: // command -> "\underline", overlay, optional
{ // beamer actually doesn't support this but we do :D
                                        CurrentSemanticValue.documentNode = new Node("underline");
                                        CurrentSemanticValue.documentNode.OverlaySpec = ValueStack[ValueStack.Depth-2].Text;
                                        CurrentSemanticValue.documentNode.OptionalParams = ValueStack[ValueStack.Depth-1].Text;
                                    }
        break;
      case 55: // command -> "\textcolor", overlay, optional, '{', "plain text", '}'
{
                                        CurrentSemanticValue.documentNode = new Node("color");
                                        CurrentSemanticValue.documentNode.OverlaySpec = ValueStack[ValueStack.Depth-5].Text;
                                        CurrentSemanticValue.documentNode.OptionalParams = ValueStack[ValueStack.Depth-4].Text;
                                        CurrentSemanticValue.documentNode.Content = ValueStack[ValueStack.Depth-2].Text as object;
                                    }
        break;
      case 56: // groupcommand -> "\bfseries"
{
                                        CurrentSemanticValue.documentNode = new Node("bold");
                                    }
        break;
      case 57: // groupcommand -> "\ttfamily"
{
                                        CurrentSemanticValue.documentNode = new Node("typewriter");
                                    }
        break;
      case 58: // groupcommand -> "\itshape"
{
                                        CurrentSemanticValue.documentNode = new Node("italic");
                                    }
        break;
      case 59: // groupcommand -> "\scshape"
{
                                        CurrentSemanticValue.documentNode = new Node("smallcaps");
                                    }
        break;
      case 60: // groupcommand -> "\tiny"
{
                                        CurrentSemanticValue.documentNode = new Node("tiny");
                                    }
        break;
      case 61: // groupcommand -> "\scriptsize"
{
                                        CurrentSemanticValue.documentNode = new Node("scriptsize");
                                    }
        break;
      case 62: // groupcommand -> "\footnotesize"
{
                                        CurrentSemanticValue.documentNode = new Node("footnotesize");
                                    }
        break;
      case 63: // groupcommand -> "\small"
{
                                        CurrentSemanticValue.documentNode = new Node("small");
                                    }
        break;
      case 64: // groupcommand -> "\normalsize"
{
                                        CurrentSemanticValue.documentNode = new Node("normalsize");
                                    }
        break;
      case 65: // groupcommand -> "\large"
{
                                        CurrentSemanticValue.documentNode = new Node("large");
                                    }
        break;
      case 66: // groupcommand -> "\Large"
{
                                        CurrentSemanticValue.documentNode = new Node("Large");
                                    }
        break;
      case 67: // groupcommand -> "\LARGE"
{
                                        CurrentSemanticValue.documentNode = new Node("LARGE");
                                    }
        break;
      case 68: // groupcommand -> "\huge"
{
                                        CurrentSemanticValue.documentNode = new Node("huge");
                                    }
        break;
      case 69: // groupcommand -> "\Huge"
{
                                        CurrentSemanticValue.documentNode = new Node("Huge");
                                    }
        break;
      case 70: // groupcommand -> "\color", overlay, optional, '{', "plain text", '}'
{
                                        CurrentSemanticValue.documentNode = new Node("color");
                                        CurrentSemanticValue.documentNode.OverlaySpec = ValueStack[ValueStack.Depth-5].Text;
                                        CurrentSemanticValue.documentNode.OptionalParams = ValueStack[ValueStack.Depth-4].Text;
                                        CurrentSemanticValue.documentNode.Content = ValueStack[ValueStack.Depth-2].Text as object;
                                    }
        break;
      case 71: // standalonecommand -> "\today"
{
                                        CurrentSemanticValue.documentNode = new Node("today");
                                    }
        break;
      case 72: // standalonecommand -> "\pause"
{
                                        CurrentSemanticValue.documentNode = new Node("pause");
                                    }
        break;
      case 73: // standalonecommand -> "\frametitle", overlay, optional, '{', simpleformtext, '}'
{
                                        SetFrameTitle(SlideCount + 1, ValueStack[ValueStack.Depth-2].nodeList, ValueStack[ValueStack.Depth-5].Text);
                                        CurrentSemanticValue.documentNode = null;
                                    }
        break;
      case 74: // standalonecommand -> "\framesubtitle", overlay, optional, '{', simpleformtext, 
               //                      '}'
{
                                        SetFrameSubtitle(SlideCount + 1, ValueStack[ValueStack.Depth-2].nodeList, ValueStack[ValueStack.Depth-5].Text);
                                        CurrentSemanticValue.documentNode = null;
                                    }
        break;
      case 75: // standalonecommand -> "\\ or \cr"
{
                                        CurrentSemanticValue.documentNode = new Node("paragraph");
                                    }
        break;
      case 76: // optional -> /* empty */
{
                                        CurrentSemanticValue.Text = "";
                                    }
        break;
      case 77: // optional -> "optional parameter"
{
                                        CurrentSemanticValue.Text = ValueStack[ValueStack.Depth-1].Text;
                                    }
        break;
      case 78: // overlay -> /* empty */
{
                                        CurrentSemanticValue.Text = "";
                                    }
        break;
      case 79: // overlay -> "overlay specification"
{
                                        CurrentSemanticValue.Text = ValueStack[ValueStack.Depth-1].Text;
                                    }
        break;
      case 80: // simpleformtext -> /* empty */
{
                                        CurrentSemanticValue.nodeList = new List<Node>();
                                    }
        break;
      case 81: // simpleformtext -> simpleformtext, command, '{', simpleformtext, '}'
{
                                        ValueStack[ValueStack.Depth-4].documentNode.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                        ValueStack[ValueStack.Depth-5].nodeList.Add(ValueStack[ValueStack.Depth-4].documentNode);
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-5].nodeList;
                                    }
        break;
      case 82: // simpleformtext -> simpleformtext, groupcommand, simpleformtext
{
                                        ValueStack[ValueStack.Depth-2].documentNode.Children = ValueStack[ValueStack.Depth-1].nodeList;
                                        ValueStack[ValueStack.Depth-3].nodeList.Add(ValueStack[ValueStack.Depth-2].documentNode);
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-3].nodeList;
                                    }
        break;
      case 83: // simpleformtext -> simpleformtext, "plain text"
{
                                        Node tmp = new Node("string");
                                        tmp.Content = ValueStack[ValueStack.Depth-1].Text as object;
                                        ValueStack[ValueStack.Depth-2].nodeList.Add(tmp);
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 84: // simpleformtext -> simpleformtext, "\\ or \cr"
{
                                        ValueStack[ValueStack.Depth-2].nodeList.Add(new Node("paragraph"));
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 85: // simpleformtext -> simpleformtext, '{', simpleformtext, '}'
{
                                        Node tmp = new Node("block");
                                        tmp.Children = ValueStack[ValueStack.Depth-2].nodeList;
                                        ValueStack[ValueStack.Depth-4].nodeList.Add(tmp);
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-4].nodeList;
                                    }
        break;
      case 86: // simpleformtext -> simpleformtext, "\today"
{
                                        ValueStack[ValueStack.Depth-2].nodeList.Add(new Node("today"));
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 87: // simpleformtext -> simpleformtext, "\pause"
{
                                        ValueStack[ValueStack.Depth-2].nodeList.Add(new Node("pause"));
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
      case 88: // simpleformtext -> simpleformtext, "\and"
{
                                        ValueStack[ValueStack.Depth-2].nodeList.Add(new Node("and"));
                                        CurrentSemanticValue.nodeList = ValueStack[ValueStack.Depth-2].nodeList;
                                    }
        break;
    }
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }


public Parser(Scanner scn) : base(scn) {
    SlideCount = 0;
    SectionTable = new List<SectionRecord>();
    FrametitleTable = new Dictionary<int, FrametitleRecord>();
}

/// <summary>
/// Set frame title
/// </summary>
/// <param name="slide">Slide number</param>
/// <param name="content">Frame title content</param>
private void SetFrameTitle(int slide, List<Node> content, string overlay = "") {
    if(content == null || content.Count == 0)
        return;
    if(FrametitleTable.ContainsKey(slide)) {    // key exist change value
        FrametitleTable[slide].Title = content;
        FrametitleTable[slide].TitleOverlay = overlay;
    } else {    // key doesn't exist create new record
        FrametitleTable.Add(slide, new FrametitleRecord(content, null));
        FrametitleTable[slide].TitleOverlay = overlay;
    }
}

/// <summary>
/// Set frame subtitle
/// </summary>
/// <param name="slide">Slide number</param>
/// <param name="content">Frame subtitle content</param>
private void SetFrameSubtitle(int slide, List<Node> content, string overlay = "") {
    if(content == null || content.Count == 0)
        return;
    if(FrametitleTable.ContainsKey(slide)) {    // key exist change value
        FrametitleTable[slide].Subtitle = content;
        FrametitleTable[slide].SubtitleOverlay = overlay;
    } else {    // key doesn't exist create new record
        FrametitleTable.Add(slide, new FrametitleRecord(null, content));
        FrametitleTable[slide].SubtitleOverlay = overlay;
    }
}
}
}
